//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LT.Recall.Cli.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LT.Recall.Cli.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted {0}..
        /// </summary>
        public static string CommandsDeletedMessage {
            get {
                return ResourceManager.GetString("CommandsDeletedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started in test mode. Press ENTER to continue (process id is {0})..
        /// </summary>
        public static string DebugMessage {
            get {
                return ResourceManager.GetString("DebugMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled..
        /// </summary>
        public static string DeleteAbortedMessage {
            get {
                return ResourceManager.GetString("DeleteAbortedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -c, --collection    	storage collection.
        ///-t, --tags 		tags (command separated).
        ///
        ///usage:
        ///	delete -c &quot;Linux&quot; -t &quot;Linux,IO&quot;.
        /// </summary>
        public static string DeleteHelpText {
            get {
                return ResourceManager.GetString("DeleteHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No commands found..
        /// </summary>
        public static string DeleteNoCommandsFoundMessage {
            get {
                return ResourceManager.GetString("DeleteNoCommandsFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Text: .
        /// </summary>
        public static string EnterCommandTextMessage {
            get {
                return ResourceManager.GetString("EnterCommandTextMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description: .
        /// </summary>
        public static string EnterDescriptionMessage {
            get {
                return ResourceManager.GetString("EnterDescriptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags (Comma Separated): .
        /// </summary>
        public static string EnterTagsMessage {
            get {
                return ResourceManager.GetString("EnterTagsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -p, --path	absolute path.
        ///
        ///usage:
        ///	export -p &quot;C:\bin\export.csv&quot;.
        /// </summary>
        public static string ExportHelpText {
            get {
                return ResourceManager.GetString("ExportHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export commands..
        /// </summary>
        public static string ExportVerbHelpText {
            get {
                return ResourceManager.GetString("ExportVerbHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -v, --verbose	enable verbose output.
        ///-h, --help	show help.
        ///
        ///save	Save a new command.
        ///search	Search commands.
        ///delete	Delete commands.
        ///import	Import commands.
        ///export	Export commands.
        ///stats	Storage statistics.
        ///install	Install collections..
        /// </summary>
        public static string HelpText {
            get {
                return ResourceManager.GetString("HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -p, --path	absolute path.
        ///
        ///usage:
        ///	import -p &quot;C:\bin\import.csv&quot;.
        /// </summary>
        public static string ImportHelpText {
            get {
                return ResourceManager.GetString("ImportHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -l, --listAll	list installers.
        ///
        ///usage:
        ///	install linux // install the test collection
        ///	install -l // list available installers.
        /// </summary>
        public static string InstallHelpText {
            get {
                return ResourceManager.GetString("InstallHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid arguments. Use &apos;{0} --help&apos; for details..
        /// </summary>
        public static string InvalidArgumentsError {
            get {
                return ResourceManager.GetString("InvalidArgumentsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List installers and collections..
        /// </summary>
        public static string ListAllOptionHelpText {
            get {
                return ResourceManager.GetString("ListAllOptionHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make selection and press ENTER or CTRL+C to exit..
        /// </summary>
        public static string MakeSelectionMessage {
            get {
                return ResourceManager.GetString("MakeSelectionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete {0} command(s)? [Y/N]:.
        /// </summary>
        public static string PreviewDeleteMessage {
            get {
                return ResourceManager.GetString("PreviewDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -c, --collection    storage collection.
        ///
        ///usage: 
        ///    save -c &quot;infrastructure&quot;.
        /// </summary>
        public static string SaveHelpText {
            get {
                return ResourceManager.GetString("SaveHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved command: {0}.
        /// </summary>
        public static string SaveSuccessMessage {
            get {
                return ResourceManager.GetString("SaveSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to use the arrow keys then press ENTER to copy to the clipboard..
        /// </summary>
        public static string SearchHelpText {
            get {
                return ResourceManager.GetString("SearchHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show storage statistics..
        /// </summary>
        public static string StatsHelpText {
            get {
                return ResourceManager.GetString("StatsHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occurred..
        /// </summary>
        public static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable verbose output..
        /// </summary>
        public static string VerboseOptionHelpText {
            get {
                return ResourceManager.GetString("VerboseOptionHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start in test mode..
        /// </summary>
        public static string XTestOptionHelpText {
            get {
                return ResourceManager.GetString("XTestOptionHelpText", resourceCulture);
            }
        }
    }
}
