//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LT.Recall.Application.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LT.Recall.Application.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} command(s) matching &apos;{1}&apos;.
        /// </summary>
        internal static string CommandSearchResultsFoundMessage {
            get {
                return ResourceManager.GetString("CommandSearchResultsFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No commands found matching &apos;{0}&apos;.
        /// </summary>
        internal static string CommandSearchResultsNotFoundMessage {
            get {
                return ResourceManager.GetString("CommandSearchResultsNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command is required.
        /// </summary>
        internal static string CommandTextMissingError {
            get {
                return ResourceManager.GetString("CommandTextMissingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description is required.
        /// </summary>
        internal static string DescriptionMissingError {
            get {
                return ResourceManager.GetString("DescriptionMissingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A command with the same command text already exists within the collection..
        /// </summary>
        internal static string DuplicateCommandError {
            get {
                return ResourceManager.GetString("DuplicateCommandError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exported {0}..
        /// </summary>
        internal static string ExportedMessage {
            get {
                return ResourceManager.GetString("ExportedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File path is required..
        /// </summary>
        internal static string FilePathIsRequiredError {
            get {
                return ResourceManager.GetString("FilePathIsRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imported {0}. Updated {1}..
        /// </summary>
        internal static string ImportedMessage {
            get {
                return ResourceManager.GetString("ImportedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input requires value &apos;{0}&apos;.
        /// </summary>
        internal static string InputRequiresValueError {
            get {
                return ResourceManager.GetString("InputRequiresValueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation completed successfully. Updated {0}. Imported {1}..
        /// </summary>
        internal static string InstallSuccessMessage {
            get {
                return ResourceManager.GetString("InstallSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection or tags is required..
        /// </summary>
        internal static string MissingDeleteParametersError {
            get {
                return ResourceManager.GetString("MissingDeleteParametersError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported file type. Supported file types are [{0}]..
        /// </summary>
        internal static string UnsupportedFileTypeError {
            get {
                return ResourceManager.GetString("UnsupportedFileTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid request.
        /// </summary>
        internal static string ValidationError {
            get {
                return ResourceManager.GetString("ValidationError", resourceCulture);
            }
        }
    }
}
