<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="envdte" />
	<PackageReference Include="envdte80" />
	<PackageReference Include="FluentAssertions" />
	<PackageReference Include="Microsoft.NET.Test.Sdk" />
	<PackageReference Include="NUnit" />
	<PackageReference Include="NUnit3TestAdapter" />
	<PackageReference Include="NUnit.Analyzers">
	  <PrivateAssets>all</PrivateAssets>
	  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	</PackageReference>
	<PackageReference Include="coverlet.collector">
	  <PrivateAssets>all</PrivateAssets>
	  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	</PackageReference>
  </ItemGroup>

	<ItemGroup>
		<Content Include="TestFiles\**">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
	  <None Remove="TestFiles\Import\002_contains-duplicate-id.csv" />
	  <None Remove="TestFiles\Import\003_command_with_commas.csv" />
	</ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\LT.Recall.Cli\LT.Recall.Cli.csproj" />
  </ItemGroup>

</Project>
