name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      checks: write

    env:
      BUILD_VERSION: ${{ github.ref_name }}

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Install dependencies
        run: dotnet restore
      
      - name: Build
        run: dotnet build --no-restore
      
      - name: Run Tests
        run: dotnet test --no-restore --logger trx --results-directory "${{ github.workspace }}/TestResults"
      
      - name: Upload dotnet test results
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: test-results
          path: "${{ github.workspace }}/TestResults"
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}
      
      - name: Test Report
        uses: dorny/test-reporter@a43b3a5f7366b97d083190328d2c652e1a8b6aa2
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: Test Report            # Name of the check run which will be created
          path: "${{ github.workspace }}/TestResults/*.trx"    # Path to test results
          reporter: dotnet-trx        # Format of test results

      - name: Publish
        run: |
          BUILD_VERSION="${BUILD_VERSION#v}"

          echo "Building version: ${BUILD_VERSION}"

          dotnet publish "./src/LT.Recall.Cli/LT.Recall.Cli.csproj" \
            --configuration Release \
            --runtime win-x64 \
            -p:PublishSingleFile=true \
            -p:PublishReadyToRun=true \
            -p:Version="${BUILD_VERSION}" \
            -p:InformationVersion="${BUILD_VERSION}" \
            -p:IncludeSourceRevisionInInformationalVersion=false

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: recall-win-x64
          path: src/LT.Recall.Cli/bin/Release/net10.0/win-x64/publish/recall.exe